wininst: Fix GIRepository version error
Due to changes in GLib, python-gobject now ships with two versions of
GIRepository. This causes `depcheck.py` to softlock during the build
process with the following error:

> gi.repository.GLib.GError: g-irepository-error-quark: Typelib file for namespace 'GIRepository', version '3.0' not found (0)

Adding a try/except in `_get_shared_libraries()` lets us ignore the
new GIRepository and the build runs properly.

---

The cause seems to be a combination of several factors.

1. The Gnome project has moved _GIRepository_ from
_GObject Introspection_ to _GLib_ and bumped its version to 3.0.
(~ GLib 2.79.0 release notes)
2. _GObject Introspection_ still provides _GIRepository 2.0_
3.  `mingw-w64-ucrt-x86_64-python-gobject` installs both _GIRepository_
2.0 and 3.0 through its dependencies.
4. To make a list of shared libraries `depcheck.py` lists all the files
in the typelib directory. This includes both `GIRepository-2.0.typelib`
and `GIRepository-3.0.typelib`
5. Since `builddep.py` require _GIRepository 2.0_, I think this blocks
3.0 from loading, so
`_get_shared_libraries(q, "GIRepository", "3.0")` fails at
`repo.require()`.